### ISSUE TITLE
Delay in monitor status - on purpose? Service calls seems strange, no entity?

### ISSUE THREAD

**Issue by fribse** [sindrebroch/ha-magicmirror#3]
## Version of the custom_component

1.4.1

## Configuration

![billede](https://user-images.githubusercontent.com/13660621/153779162-9b07eb80-846e-4915-bce8-53103c1cb679.png)

## Describe the bug
When I turn the monitor on or off, there is a delay on the status shown in Lovelace.
Is it 'as designed' or is it a fluke?

The services set up in the integration doesn't show any entity requirement when looking in 'developer tools', which seems like a problem :-)

![billede](https://user-images.githubusercontent.com/13660621/153779219-9cdd5a3b-536f-4ddd-8268-837c5d12a7a8.png)

P.S. I am SUPER excited that you made this integration, it's simply fantastic to not have to set up MQTTBridge like I've had for years now.

**Comment by fribse** [comment]
Ahh, ok, I can see that you are removing the special service calls, so that part is at least making sense, is the removal of 'binary_sensor' part the reason for the delay in status, it reads the status of the mirror, and with the new switch entity you are going to make it 'optimistic' in the sense that the switch will hold the status itself, and just hope the mirror agrees?

**Comment by sindrebroch** [comment]
I'm sure there are some optimizations possible to make the switch more responsive. I will take a look at it. I wrote the integration without much experience, but in theory it should fetch new state after POST, so it might just be the delay from the next status-fetch. Making it optimistic might be the best way out if there are no other glaring issues.

Will at it to my internal todo

**Comment by sindrebroch** [comment]
And also most of the service calls will be deprecated to be replaced by buttons per MagicMirror. For whatever service calls are left I might need a entity, hadn't though of that. Not sure how the integration handles multiple magicmirrors to be honest.

**Comment by fribse** [comment]
Well, the optimistic approach will of course give faster status updates, as it doesn't check the real status, problem is though, that if the monitor is turned on or off locally, the switch will not reflect that if it's optimistic, so it's a bit damned if you do, and damned if you don't 😆

**Comment by sindrebroch** [comment]
For sure, I'll try to do some tweaks and see what works best. Maybe we can do optimistic but update if it fails or something?

**Comment by fribse** [comment]
Yes, that would probably work well if it's doable.

**Comment by sindrebroch** [comment]
I have released a pre-release [v1.2.0b0](https://github.com/sindrebroch/ha-magicmirror/tree/v1.2.0b0), which contains optimistic switch as well as some other improvements. All the services have been removed as well, now replaced with button-entities and notify-service. Again not 100% sure how the integration would handle multiple instances, but I'll tackle that at some later time.

I like to test the new releases for a few days before I properly release them, but you can update it to try if you want.

**Comment by sindrebroch** [comment]
Should be solved by [release 1.2.0](https://github.com/sindrebroch/ha-magicmirror/releases/tag/1.2.0)
